version: '3.3'
services:
  ldes-client:
    ports:
      - '8443:8443'
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    image: ldes-client