services:
  sink:
    image: vsds/e2e-test-sink
    build:
      context: ./sink
    ports:
      - "9003:80"
    networks:
      - e2e-test
  replicate-workflow:
    image: vsds/nifi
    build:
      context: ..
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    ports:
      - "8443:8443"
      - "9002:8080"
    volumes:
      - ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./nifi/conf:/opt/nifi/nifi-current/conf
    networks:
      - e2e-test
  gipod-simulator:
    image: vsds/gipod-simuator
    # TODO: use pre-built container (i.e. image: not build:)
    build:
      context: ../../VSDS-LDESServerSimulator
    ports:
      - "9001:80"
    environment:
      - BASEURL=http://gipod-simulator
      - SEED=data/gipod
    networks:
      - e2e-test

networks:
  e2e-test: {}
